[project]
name = "agendafy"
plan = "free"

[api]
enabled = true
port = 54321

[analytics]
enabled = false

[functions]
enabled = true
verify_jwt = false

[functions."send-whatsapp"]
verify_jwt = false
import_map = "./functions/send-whatsapp/deno.json"
